import {MigrationInterface, QueryRunner} from "typeorm";

export class migration1611990113471 implements MigrationInterface {
    name = 'migration1611990113471'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `category_entity` DROP FOREIGN KEY `FK_4e2dfe2419b338e206fce7d625f`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP FOREIGN KEY `FK_c18323cdfaaf802bdb1e8f233af`");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP FOREIGN KEY `FK_1d51f239cf127f7e233976dbff1`");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP FOREIGN KEY `FK_4b42fedc1fcec26699c063eb824`");
        await queryRunner.query("DROP INDEX `IDX_ac2c729b9c4e325c599172e49c` ON `budget_entity`");
        await queryRunner.query("ALTER TABLE `category_template_entity` CHANGE `templateId` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("CREATE TABLE `budget_entity_months_budget_month_entity` (`budgetEntityId` varchar(36) NOT NULL, `budgetMonthEntityId` int NOT NULL, INDEX `IDX_a14b6c7c45e9e84fde433c0666` (`budgetEntityId`), INDEX `IDX_62840da010415532959f35fdae` (`budgetMonthEntityId`), PRIMARY KEY (`budgetEntityId`, `budgetMonthEntityId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `incomeCategoriesTemplateId`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `outcomeCategoriesTemplateId`");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP COLUMN `monthCategoryTemplateId`");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP COLUMN `budgetMonthId`");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP COLUMN `budgetId`");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `incomeCategoriesId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `outcomeCategoriesId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD `monthCategoryId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP FOREIGN KEY `FK_d2483a8174e467ff9a3505e59cc`");
        await queryRunner.query("ALTER TABLE `child_category_entity` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP COLUMN `categoryId`");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD `categoryId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `category_entity` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `category_entity` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP FOREIGN KEY `FK_0fcde7c1a1ac3938d0700ef87b4`");
        await queryRunner.query("ALTER TABLE `category_template_entity` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP COLUMN `userId`");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD `userId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP FOREIGN KEY `FK_417f3146297873da11a8d24d7f6`");
        await queryRunner.query("ALTER TABLE `budget_entity` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD `id` varchar(36) NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP COLUMN `userId`");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD `userId` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `user_entity` CHANGE `id` `id` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD CONSTRAINT `FK_d2483a8174e467ff9a3505e59cc` FOREIGN KEY (`categoryId`) REFERENCES `category_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_entity` ADD CONSTRAINT `FK_1f5756f78b190c0ed25673420dc` FOREIGN KEY (`incomeCategoriesId`) REFERENCES `category_template_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_entity` ADD CONSTRAINT `FK_edc3126d323f4df2c4b4e031d1e` FOREIGN KEY (`outcomeCategoriesId`) REFERENCES `category_template_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD CONSTRAINT `FK_8a87be594283fd46276ca7a855b` FOREIGN KEY (`monthCategoryId`) REFERENCES `category_template_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD CONSTRAINT `FK_0fcde7c1a1ac3938d0700ef87b4` FOREIGN KEY (`userId`) REFERENCES `user_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD CONSTRAINT `FK_417f3146297873da11a8d24d7f6` FOREIGN KEY (`userId`) REFERENCES `user_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_entity_months_budget_month_entity` ADD CONSTRAINT `FK_a14b6c7c45e9e84fde433c0666f` FOREIGN KEY (`budgetEntityId`) REFERENCES `budget_entity`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_entity_months_budget_month_entity` ADD CONSTRAINT `FK_62840da010415532959f35fdae2` FOREIGN KEY (`budgetMonthEntityId`) REFERENCES `budget_month_entity`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `budget_entity_months_budget_month_entity` DROP FOREIGN KEY `FK_62840da010415532959f35fdae2`");
        await queryRunner.query("ALTER TABLE `budget_entity_months_budget_month_entity` DROP FOREIGN KEY `FK_a14b6c7c45e9e84fde433c0666f`");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP FOREIGN KEY `FK_417f3146297873da11a8d24d7f6`");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP FOREIGN KEY `FK_0fcde7c1a1ac3938d0700ef87b4`");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP FOREIGN KEY `FK_8a87be594283fd46276ca7a855b`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP FOREIGN KEY `FK_edc3126d323f4df2c4b4e031d1e`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP FOREIGN KEY `FK_1f5756f78b190c0ed25673420dc`");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP FOREIGN KEY `FK_d2483a8174e467ff9a3505e59cc`");
        await queryRunner.query("ALTER TABLE `user_entity` CHANGE `id` `id` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP COLUMN `userId`");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD `userId` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `budget_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `budget_entity` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD CONSTRAINT `FK_417f3146297873da11a8d24d7f6` FOREIGN KEY (`userId`) REFERENCES `user_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP COLUMN `userId`");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD `userId` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `category_template_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `category_template_entity` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `category_template_entity` ADD CONSTRAINT `FK_0fcde7c1a1ac3938d0700ef87b4` FOREIGN KEY (`userId`) REFERENCES `user_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `budget_plan_summary_entity` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `category_entity` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `category_entity` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP COLUMN `categoryId`");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD `categoryId` int NULL");
        await queryRunner.query("ALTER TABLE `child_category_entity` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `child_category_entity` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `child_category_entity` ADD CONSTRAINT `FK_d2483a8174e467ff9a3505e59cc` FOREIGN KEY (`categoryId`) REFERENCES `category_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_month_entity` DROP COLUMN `monthCategoryId`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `outcomeCategoriesId`");
        await queryRunner.query("ALTER TABLE `category_entity` DROP COLUMN `incomeCategoriesId`");
        await queryRunner.query("ALTER TABLE `budget_entity` ADD `budgetId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD `budgetMonthId` int NULL");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD `monthCategoryTemplateId` int NULL");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `outcomeCategoriesTemplateId` int NULL");
        await queryRunner.query("ALTER TABLE `category_entity` ADD `incomeCategoriesTemplateId` int NULL");
        await queryRunner.query("DROP INDEX `IDX_62840da010415532959f35fdae` ON `budget_entity_months_budget_month_entity`");
        await queryRunner.query("DROP INDEX `IDX_a14b6c7c45e9e84fde433c0666` ON `budget_entity_months_budget_month_entity`");
        await queryRunner.query("DROP TABLE `budget_entity_months_budget_month_entity`");
        await queryRunner.query("ALTER TABLE `category_template_entity` CHANGE `id` `templateId` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("CREATE UNIQUE INDEX `IDX_ac2c729b9c4e325c599172e49c` ON `budget_entity` (`budgetId`)");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD CONSTRAINT `FK_4b42fedc1fcec26699c063eb824` FOREIGN KEY (`monthCategoryTemplateId`) REFERENCES `category_template_entity`(`templateId`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `budget_month_entity` ADD CONSTRAINT `FK_1d51f239cf127f7e233976dbff1` FOREIGN KEY (`budgetMonthId`) REFERENCES `budget_entity`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_entity` ADD CONSTRAINT `FK_c18323cdfaaf802bdb1e8f233af` FOREIGN KEY (`incomeCategoriesTemplateId`) REFERENCES `category_template_entity`(`templateId`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category_entity` ADD CONSTRAINT `FK_4e2dfe2419b338e206fce7d625f` FOREIGN KEY (`outcomeCategoriesTemplateId`) REFERENCES `category_template_entity`(`templateId`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

}
